### ISSUE TITLE
Question from a noob

### ISSUE THREAD

**Issue by me7pako** [MrKinau/bbb-downloader#1]
Hi,

I have a question about the tool and its dependencies: one needs ffmpeg. But how do I install them? because I get always an error when running the script:
"moov atom not found
webcams.mp4: Invalid data found when processing input" with other details.
I get this one since I manually moved the ffmpeg zip to the bbb downloader folder because if I don't, it will show:
"writing web request" where it seems to download ffmpeg I guess, but after some time it will show the following error:
"Move-Item : Cannot find path
'C:\Users\nhdnh\OneDrive\Bureau\bbb-downloader-main\ffmpeg-4.3.1-2020-11-08-full_build\bin\ffmpeg.exe' because it does
not exist.
At C:\Users\nhdnh\OneDrive\Bureau\bbb-downloader-main\downloadBBB.ps1:63 char:5
+     Move-Item -Path ".\ffmpeg-$ffmpegVersion-full_build\bin\ffmpeg.ex ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\nhdnh\...\bin\ffmpeg.exe:String) [Move-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand

Delete ffmpeg.zip...
Remove-Item : Cannot find path 'C:\Users\nhdnh\OneDrive\Bureau\bbb-downloader-main\ffmpeg-4.3.1-2020-11-08-full_build'
because it does not exist.
At C:\Users\nhdnh\OneDrive\Bureau\bbb-downloader-main\downloadBBB.ps1:66 char:5
+     Remove-Item -Recurse -Force ".\ffmpeg-$ffmpegVersion-full_build"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\nhdnh\...1-08-full_build:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Merging video and audio...
.\ffmpeg.exe : The term '.\ffmpeg.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ .\ffmpeg.exe -i webcams.mp4 -i deskshare.mp4 -c copy DSPDSP.mp4
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\ffmpeg.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException"

**Comment by MrKinau** [comment]
If the automatic download/unzipping does not work you can skip this process with downloading ffmpeg manually from [here](https://github.com/GyanD/codexffmpeg/releases/download/4.3.1-2020-11-08/ffmpeg-bbb-downloader-main-full_build.zip) and extract the ffmpeg.exe to your dir (bbb-downloader-main) It's located in the zip at ffmpeg-bbb-downloader-main-full_build/bin/ffmpeg.exe

On my machine the download/extract of ffmpeg.zip works, so I have no idea why its not working sry, but with downloading ffmpeg manually it should work. Please let me know if you have any further questions :)

**Comment by me7pako** [comment]
Hey thank you for the quick response.
Actually I did what you said but there is one error showing:
"Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001d4fecfe800] moov atom not found
webcams.mp4: Invalid data found when processing input" .
Do you have any idea what could that be ?

**Comment by MrKinau** [comment]
after some googling: The moov atom is some part at the end of a mp4 video (or should be there).

Seems like your downloaded files (deskshare.mp4 and webcams.mp4) are corrupted somehow (have you tried viewing/listening to them?)

**Comment by me7pako** [comment]
Indeed I have, the video is a white screen though. So there is only the slides and the audio. Is there any workaround?
Sorry for taking you your time.

**Comment by MrKinau** [comment]
No problem.
This script is only made to download the deskshare.mp4 (not the slides, thats handled quite crazy in BBB and is not part of the deskshare) which contains the video and the sound in webcams.mp4 (most likely the webcam streams too, but I haven't tested it, without webcam videos it was just a white screen). The script tries to merge these files together using ffmpeg, but I do not know why you get this error, if you can play the files.
If you want to download the slides this repo contains more information about it: [https://github.com/trahay/bbb-downloader](https://github.com/trahay/bbb-downloader)

**Comment by me7pako** [comment]
Thank you for your kind feedback. I will check the thread you mentioned.
Have a good evening.
